<?php
$parameters = array(
	'db_driver' => 'pdo_mysql',
	'db_host' => 'localhost',
	'db_table_prefix' => null,
	'db_port' => '3306',
	'db_name' => 'mautic',
	'db_user' => 'mautic',
	'db_password' => 'secret',
	'db_backup_tables' => 1,
	'db_backup_prefix' => 'bak_',
	'db_server_version' => '5.5.5-10.1.37-MariaDB-0+deb9u1',
	'mailer_from_name' => 'Admin Admin',
	'mailer_from_email' => 'akarasulu@optdyn.com',
	'mailer_transport' => 'mail',
	'mailer_host' => 'localhost',
	'mailer_port' => '25',
	'mailer_user' => null,
	'mailer_password' => null,
	'mailer_encryption' => null,
	'mailer_auth_mode' => null,
	'mailer_spool_type' => 'memory',
	'mailer_spool_path' => '%kernel.root_dir%/spool',
	'secret_key' => '23d10bacab16442e1abb4981463fbd964c917795c3666674e9b988796d9a72a4',
	'site_url' => 'http://localhost/mautic/index.php',
);
